### ISSUE TITLE
Add a way to load schemas on editor

### ISSUE THREAD

**Issue by tiagozaccaro** [data-driven-forms/editor#12]
Please if you cloud add a way to load a schema on the editor so we cloud edit a premade schema.

thanks.

**Comment by rvsia** [comment]
Add in the latest [commit](https://github.com/data-driven-forms/editor/commit/656b556d32755356d1c4493a67ab5dc4d51b45f2)

Read more [here](https://github.com/data-driven-forms/editor/tree/main/packages/editor-pro#initialschema)

**Comment by tiagozaccaro** [comment]
That was fast, thanks a lot for this library

**Comment by rvsia** [comment]
@tiagozaccaro No problem! 

This library is still in its early days so we welcome any feedback and help.

**Comment by tiagozaccaro** [comment]
I will use it in a project, if I have any good Idea of improvements I can share or even help if you accept

**Comment by rvsia** [comment]
@tiagozaccaro that would be awesome! We are always open to receive PRs and to help finishing them!
